os: osx
language: swift
osx_image: xcode11.3
xcode_project: Contacts.xcodeproj
xcode_scheme: Contacts
xcode_sdk: iphonesimulator13.2
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 11
after_success:
    - bash <(curl -s https://codecov.io/bash)
